"""Quantization and dequantization for all StoreDtype levels."""

from __future__ import annotations

import functools
import math

import numpy as np
from numpy.typing import NDArray

from tqvs._types import StoreDtype

# ---------------------------------------------------------------------------
# Lloyd-Max optimal centroids for N(0, 1)
# Precomputed via the iterative Lloyd-Max algorithm for the standard normal.
# For TurboQuant, these are scaled by 1/sqrt(dim) at runtime.
# ---------------------------------------------------------------------------

_LLOYD_MAX_CENTROIDS: dict[int, NDArray[np.float64]] = {
    2: np.array([-1.5104176087, -0.4527800398, 0.4527800398, 1.5104176087]),
    3: np.array([
        -2.1519775209, -1.3439092613, -0.7560052489, -0.2451209526,
        0.2451209526, 0.7560052489, 1.3439092613, 2.1519775209,
    ]),
    4: np.array([
        -2.7326368678, -2.0690790941, -1.6180334280, -1.2562297480,
        -0.9423600572, -0.6568055658, -0.3880823641, -0.1284362997,
        0.1284362997, 0.3880823641, 0.6568055658, 0.9423600572,
        1.2562297480, 1.6180334280, 2.0690790941, 2.7326368678,
    ]),
}

# ---------------------------------------------------------------------------
# Rotation matrix helpers
# ---------------------------------------------------------------------------


@functools.lru_cache(maxsize=8)
def make_rotation_matrix(dim: int, seed: int) -> NDArray[np.float64]:
    """Generate a deterministic random orthogonal matrix via QR decomposition.

    Results are cached by (dim, seed) to avoid recomputing on every store open.
    """
    rng = np.random.default_rng(seed)
    z = rng.standard_normal((dim, dim))
    q, r = np.linalg.qr(z)
    # Ensure uniform distribution (Haar measure) by fixing sign ambiguity
    d = np.sign(np.diag(r))
    d[d == 0] = 1
    q = q * d[np.newaxis, :]
    q.flags.writeable = False  # immutable since it's cached
    return q

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def quantize(
    vectors: NDArray[np.floating],
    dtype: StoreDtype,
    *,
    rotation_matrix: NDArray[np.float64] | None = None,
) -> tuple[np.ndarray, np.ndarray | None]:
    """Quantize *vectors* (float32/64, shape ``(n, dim)``) to *dtype*.

    Returns
    -------
    data : np.ndarray
        Stored representation.  Shape depends on dtype.
    quant_params : np.ndarray | None
        Per-vector parameters (scale and optionally zero-point).
        ``None`` for float dtypes.

    Parameters
    ----------
    rotation_matrix : optional
        Required for TurboQuant dtypes.  A ``(dim, dim)`` orthogonal matrix
        generated by :func:`make_rotation_matrix`.
    """
    vectors = np.asarray(vectors, dtype=np.float32)
    if vectors.ndim == 1:
        vectors = vectors[np.newaxis, :]

    match dtype:
        case StoreDtype.FLOAT64:
            return vectors.astype(np.float64), None
        case StoreDtype.FLOAT32:
            return vectors.astype(np.float32), None
        case StoreDtype.FLOAT16:
            return vectors.astype(np.float16), None
        case StoreDtype.BFLOAT16:
            return _float32_to_bfloat16(vectors), None
        case StoreDtype.INT8_SYM:
            return _quantize_int8_sym(vectors)
        case StoreDtype.INT8_ASYM:
            return _quantize_int8_asym(vectors)
        case StoreDtype.FP4:
            return _quantize_fp4(vectors)
        case StoreDtype.INT4:
            return _quantize_int4(vectors)
        case StoreDtype.INT3:
            return _quantize_int3(vectors)
        case StoreDtype.TURBO_2BIT:
            return _quantize_turbo(vectors, 2, rotation_matrix)
        case StoreDtype.TURBO_3BIT:
            return _quantize_turbo(vectors, 3, rotation_matrix)
        case StoreDtype.TURBO_4BIT:
            return _quantize_turbo(vectors, 4, rotation_matrix)
        case _:  # pragma: no cover
            raise ValueError(f"Unsupported dtype: {dtype}")


def dequantize(
    data: np.ndarray,
    dtype: StoreDtype,
    quant_params: np.ndarray | None,
    dim: int,
    *,
    rotation_matrix: NDArray[np.float64] | None = None,
) -> NDArray[np.float32]:
    """Restore float32 vectors from their stored representation.

    Parameters
    ----------
    data : stored array (shape depends on dtype).
    dtype : the StoreDtype that was used to quantize.
    quant_params : per-vector quantization params (or ``None``).
    dim : original vector dimensionality (needed for sub-byte unpacking).
    rotation_matrix : optional
        Required for TurboQuant dtypes.
    """
    match dtype:
        case StoreDtype.FLOAT64 | StoreDtype.FLOAT32 | StoreDtype.FLOAT16:
            return data.astype(np.float32)
        case StoreDtype.BFLOAT16:
            return _bfloat16_to_float32(data)
        case StoreDtype.INT8_SYM:
            return _dequantize_int8_sym(data, quant_params)
        case StoreDtype.INT8_ASYM:
            return _dequantize_int8_asym(data, quant_params)
        case StoreDtype.FP4:
            return _dequantize_fp4(data, quant_params, dim)
        case StoreDtype.INT4:
            return _dequantize_int4(data, quant_params, dim)
        case StoreDtype.INT3:
            return _dequantize_int3(data, quant_params, dim)
        case StoreDtype.TURBO_2BIT:
            return _dequantize_turbo(data, 2, quant_params, dim, rotation_matrix)
        case StoreDtype.TURBO_3BIT:
            return _dequantize_turbo(data, 3, quant_params, dim, rotation_matrix)
        case StoreDtype.TURBO_4BIT:
            return _dequantize_turbo(data, 4, quant_params, dim, rotation_matrix)
        case _:  # pragma: no cover
            raise ValueError(f"Unsupported dtype: {dtype}")


# ---------------------------------------------------------------------------
# Sub-byte packing helpers
# ---------------------------------------------------------------------------


def pack_int4(values: np.ndarray) -> np.ndarray:
    """Pack an array of signed 4-bit values (range -8..7) into uint8.

    Two values per byte: low nibble first, then high nibble.
    *values* shape ``(n, dim)`` → output shape ``(n, ceil(dim/2))``.
    """
    n, dim = values.shape
    # Pad to even length if necessary
    if dim % 2:
        values = np.concatenate(
            [values, np.zeros((n, 1), dtype=values.dtype)], axis=1
        )
    # Mask to 4-bit unsigned representation
    masked = values.astype(np.uint8) & 0x0F
    low = masked[:, 0::2]
    high = masked[:, 1::2]
    return (low | (high << 4)).astype(np.uint8)


def unpack_int4(packed: np.ndarray, dim: int) -> np.ndarray:
    """Unpack uint8 array back to signed 4-bit values.

    Returns shape ``(n, dim)`` with dtype int8.
    """
    low = (packed & 0x0F).astype(np.int8)
    high = ((packed >> 4) & 0x0F).astype(np.int8)
    # Sign-extend from 4-bit
    low = (low ^ 0x08) - 0x08
    high = (high ^ 0x08) - 0x08
    # Interleave
    n = packed.shape[0]
    interleaved = np.empty((n, packed.shape[1] * 2), dtype=np.int8)
    interleaved[:, 0::2] = low
    interleaved[:, 1::2] = high
    return interleaved[:, :dim]


def pack_int3(values: np.ndarray) -> np.ndarray:
    """Pack signed 3-bit values (range -4..3) into uint8.

    8 values are packed into 3 bytes (24 bits).
    *values* shape ``(n, dim)`` → output shape ``(n, ceil(dim/8)*3)``.
    """
    n, dim = values.shape
    # Pad to multiple of 8
    pad = (8 - dim % 8) % 8
    if pad:
        values = np.concatenate(
            [values, np.zeros((n, pad), dtype=values.dtype)], axis=1
        )
    groups = values.shape[1] // 8  # number of 8-value groups
    # Mask to 3-bit unsigned representation
    masked = values.astype(np.uint32) & 0x07  # shape (n, groups*8)
    masked = masked.reshape(n, groups, 8)  # (n, groups, 8)

    # Pack 8 × 3-bit values into 3 bytes (24 bits)
    # Bit layout: byte0 = v0[2:0]|v1[2:0]|v2[1:0], byte1 = v2[2]|v3|v4|v5[1:0], byte2 = v5[2]|v6|v7|pad[1:0]
    # Simpler: treat as a 24-bit integer, little-endian.
    bits = np.zeros((n, groups), dtype=np.uint32)
    for i in range(8):
        bits |= masked[:, :, i] << (i * 3)

    packed = np.zeros((n, groups * 3), dtype=np.uint8)
    packed[:, 0::3] = (bits & 0xFF).astype(np.uint8)
    packed[:, 1::3] = ((bits >> 8) & 0xFF).astype(np.uint8)
    packed[:, 2::3] = ((bits >> 16) & 0xFF).astype(np.uint8)
    return packed


def unpack_int3(packed: np.ndarray, dim: int) -> np.ndarray:
    """Unpack uint8 array back to signed 3-bit values.

    Returns shape ``(n, dim)`` with dtype int8.
    """
    n = packed.shape[0]
    groups = packed.shape[1] // 3

    # Reconstruct 24-bit integers
    bits = (
        packed[:, 0::3].astype(np.uint32)
        | (packed[:, 1::3].astype(np.uint32) << 8)
        | (packed[:, 2::3].astype(np.uint32) << 16)
    )

    vals = np.zeros((n, groups, 8), dtype=np.int8)
    for i in range(8):
        raw = ((bits >> (i * 3)) & 0x07).astype(np.int8)
        # Sign-extend from 3-bit
        vals[:, :, i] = (raw ^ 0x04) - 0x04

    return vals.reshape(n, groups * 8)[:, :dim]


# ---------------------------------------------------------------------------
# BFloat16 helpers (numpy has no native bfloat16)
# ---------------------------------------------------------------------------


def _float32_to_bfloat16(arr: NDArray[np.float32]) -> NDArray[np.uint16]:
    """Truncate float32 to bfloat16 stored as uint16."""
    return arr.view(np.uint32)[:, :].astype(np.uint32).__rshift__(16).astype(np.uint16)


def _bfloat16_to_float32(arr: NDArray[np.uint16]) -> NDArray[np.float32]:
    """Expand bfloat16 (uint16) back to float32."""
    wide = arr.astype(np.uint32) << 16
    return wide.view(np.float32)


# ---------------------------------------------------------------------------
# INT8 symmetric
# ---------------------------------------------------------------------------


def _quantize_int8_sym(
    vectors: NDArray[np.float32],
) -> tuple[np.ndarray, np.ndarray]:
    abs_max = np.max(np.abs(vectors), axis=1, keepdims=True)  # (n, 1)
    # Avoid division by zero
    abs_max = np.where(abs_max == 0, 1.0, abs_max)
    scale = abs_max / 127.0  # (n, 1)
    quantized = np.clip(np.round(vectors / scale), -127, 127).astype(np.int8)
    return quantized, scale.astype(np.float32)


def _dequantize_int8_sym(
    data: np.ndarray, quant_params: np.ndarray | None
) -> NDArray[np.float32]:
    assert quant_params is not None
    scale = quant_params  # (n, 1)
    return data.astype(np.float32) * scale


# ---------------------------------------------------------------------------
# INT8 asymmetric
# ---------------------------------------------------------------------------


def _quantize_int8_asym(
    vectors: NDArray[np.float32],
) -> tuple[np.ndarray, np.ndarray]:
    vmin = np.min(vectors, axis=1, keepdims=True)  # (n, 1)
    vmax = np.max(vectors, axis=1, keepdims=True)  # (n, 1)
    span = vmax - vmin
    span = np.where(span == 0, 1.0, span)
    scale = span / 255.0  # (n, 1)
    zero_point = np.clip(np.round(-vmin / scale), 0, 255)  # (n, 1)
    quantized = np.clip(np.round(vectors / scale + zero_point), 0, 255).astype(
        np.uint8
    )
    # Store as int8 view for consistency (values 0..255 stored unsigned)
    params = np.concatenate([scale, zero_point], axis=1).astype(np.float32)  # (n, 2)
    return quantized.view(np.int8), params


def _dequantize_int8_asym(
    data: np.ndarray, quant_params: np.ndarray | None
) -> NDArray[np.float32]:
    assert quant_params is not None
    scale = quant_params[:, 0:1]  # (n, 1)
    zero_point = quant_params[:, 1:2]  # (n, 1)
    return (data.view(np.uint8).astype(np.float32) - zero_point) * scale


# ---------------------------------------------------------------------------
# FP4 (E2M1 mini-float with per-vector scale)
# ---------------------------------------------------------------------------

# E2M1 codebook: 1 sign bit, 2 exponent bits, 1 mantissa bit, bias=1.
# Positive values (codes 0-7): 0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0
# Negative values (codes 8-15): -0, -0.5, -1.0, -1.5, -2.0, -3.0, -4.0, -6.0
_FP4_TABLE = np.array(
    [0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0,
     -0.0, -0.5, -1.0, -1.5, -2.0, -3.0, -4.0, -6.0],
    dtype=np.float32,
)

# Sorted positive representable values and their midpoint boundaries
_FP4_POS_VALS = np.array([0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0], dtype=np.float32)
_FP4_POS_BOUNDS = (_FP4_POS_VALS[:-1] + _FP4_POS_VALS[1:]) / 2  # midpoints


def _quantize_fp4(
    vectors: NDArray[np.float32],
) -> tuple[np.ndarray, np.ndarray]:
    abs_max = np.max(np.abs(vectors), axis=1, keepdims=True)
    abs_max = np.where(abs_max == 0, 1.0, abs_max)
    scale = abs_max / 6.0  # (n, 1) — 6.0 is the largest FP4 magnitude
    scaled = vectors / scale  # (n, dim)

    signs = (scaled < 0).astype(np.uint8)  # 0 or 1
    abs_scaled = np.abs(scaled)  # (n, dim)

    # Nearest FP4 code via searchsorted on positive boundaries
    codes = np.searchsorted(_FP4_POS_BOUNDS, abs_scaled).astype(np.uint8)  # 0..7
    codes = (signs << 3) | codes  # 4-bit FP4 code

    packed = pack_fp4(codes)
    return packed, scale.astype(np.float32)


def _dequantize_fp4(
    data: np.ndarray, quant_params: np.ndarray | None, dim: int
) -> NDArray[np.float32]:
    assert quant_params is not None
    scale = quant_params[:, 0:1]  # (n, 1)
    codes = unpack_fp4(data, dim)  # (n, dim) uint8 0..15
    return _FP4_TABLE[codes] * scale


def pack_fp4(codes: np.ndarray) -> np.ndarray:
    """Pack 4-bit FP4 codes (0..15) into uint8.

    Two values per byte: low nibble first.
    *codes* shape ``(n, dim)`` → ``(n, ceil(dim/2))``.
    """
    n, dim = codes.shape
    if dim % 2:
        codes = np.concatenate(
            [codes, np.zeros((n, 1), dtype=codes.dtype)], axis=1
        )
    low = codes[:, 0::2].astype(np.uint8)
    high = codes[:, 1::2].astype(np.uint8)
    return (low | (high << 4)).astype(np.uint8)


def unpack_fp4(packed: np.ndarray, dim: int) -> np.ndarray:
    """Unpack uint8 array back to 4-bit FP4 codes (0..15).

    Returns shape ``(n, dim)`` with dtype uint8.
    """
    low = packed & 0x0F
    high = (packed >> 4) & 0x0F
    n = packed.shape[0]
    interleaved = np.empty((n, packed.shape[1] * 2), dtype=np.uint8)
    interleaved[:, 0::2] = low
    interleaved[:, 1::2] = high
    return interleaved[:, :dim]


# ---------------------------------------------------------------------------
# INT4 symmetric
# ---------------------------------------------------------------------------


def _quantize_int4(
    vectors: NDArray[np.float32],
) -> tuple[np.ndarray, np.ndarray]:
    abs_max = np.max(np.abs(vectors), axis=1, keepdims=True)
    abs_max = np.where(abs_max == 0, 1.0, abs_max)
    scale = abs_max / 7.0  # (n, 1)  -- 4-bit signed range is -8..7
    quantized = np.clip(np.round(vectors / scale), -8, 7).astype(np.int8)
    packed = pack_int4(quantized)
    return packed, scale.astype(np.float32)


def _dequantize_int4(
    data: np.ndarray, quant_params: np.ndarray | None, dim: int
) -> NDArray[np.float32]:
    assert quant_params is not None
    scale = quant_params[:, 0:1]  # (n, 1)
    unpacked = unpack_int4(data, dim)
    return unpacked.astype(np.float32) * scale


# ---------------------------------------------------------------------------
# INT3 symmetric
# ---------------------------------------------------------------------------


def _quantize_int3(
    vectors: NDArray[np.float32],
) -> tuple[np.ndarray, np.ndarray]:
    abs_max = np.max(np.abs(vectors), axis=1, keepdims=True)
    abs_max = np.where(abs_max == 0, 1.0, abs_max)
    scale = abs_max / 3.0  # (n, 1)  -- 3-bit signed range is -4..3
    quantized = np.clip(np.round(vectors / scale), -4, 3).astype(np.int8)
    packed = pack_int3(quantized)
    return packed, scale.astype(np.float32)


def _dequantize_int3(
    data: np.ndarray, quant_params: np.ndarray | None, dim: int
) -> NDArray[np.float32]:
    assert quant_params is not None
    scale = quant_params[:, 0:1]  # (n, 1)
    unpacked = unpack_int3(data, dim)
    return unpacked.astype(np.float32) * scale


# ---------------------------------------------------------------------------
# TurboQuant — random rotation + Lloyd-Max scalar quantization
# ---------------------------------------------------------------------------


def _get_turbo_codebook(bits: int, dim: int) -> NDArray[np.float64]:
    """Return sorted Lloyd-Max centroids scaled for dimension *dim*.

    The centroids are optimal for N(0, 1/dim) — the distribution of each
    coordinate after random rotation of a unit-norm vector in R^dim.
    """
    base = _LLOYD_MAX_CENTROIDS[bits]
    return base / math.sqrt(dim)


def _quantize_turbo(
    vectors: NDArray[np.float32],
    bits: int,
    rotation_matrix: NDArray[np.float64] | None,
) -> tuple[np.ndarray, np.ndarray]:
    """TurboQuant quantization: rotate → scalar-quantize each coordinate.

    Returns ``(packed_indices, norms)`` where *norms* has shape ``(n, 1)``.
    """
    if rotation_matrix is None:
        raise ValueError("rotation_matrix is required for TurboQuant dtypes")
    n, dim = vectors.shape
    # Normalise to unit norm; store norms as quant_params
    norms = np.linalg.norm(vectors, axis=1, keepdims=True).astype(np.float32)
    safe_norms = np.where(norms == 0, 1.0, norms)
    normalised = vectors / safe_norms  # (n, dim)

    # Rotate
    rot = rotation_matrix.astype(np.float32)
    rotated = normalised @ rot.T  # (n, dim)

    # Lloyd-Max scalar quantization per coordinate
    codebook = _get_turbo_codebook(bits, dim).astype(np.float32)  # (2^bits,)
    num_levels = len(codebook)
    # Boundaries are midpoints between consecutive centroids
    boundaries = (codebook[:-1] + codebook[1:]) / 2  # (2^bits - 1,)
    # np.searchsorted gives the index of the first boundary > value,
    # which is exactly the cluster index when centroids are sorted.
    indices = np.searchsorted(boundaries, rotated).astype(np.uint8)  # (n, dim)

    # Pack indices using the appropriate sub-byte packer
    if bits == 2:
        packed = _pack_turbo2(indices)
    elif bits == 3:
        packed = _pack_turbo3(indices)
    else:  # bits == 4
        packed = _pack_turbo4(indices)

    return packed, norms


def _dequantize_turbo(
    data: np.ndarray,
    bits: int,
    quant_params: np.ndarray | None,
    dim: int,
    rotation_matrix: NDArray[np.float64] | None,
) -> NDArray[np.float32]:
    """TurboQuant dequantization: unpack → lookup centroids → inverse-rotate → rescale."""
    assert quant_params is not None
    if rotation_matrix is None:
        raise ValueError("rotation_matrix is required for TurboQuant dtypes")

    norms = quant_params  # (n, 1)

    # Unpack indices
    if bits == 2:
        indices = _unpack_turbo2(data, dim)
    elif bits == 3:
        indices = _unpack_turbo3(data, dim)
    else:  # bits == 4
        indices = _unpack_turbo4(data, dim)

    # Reconstruct from codebook
    codebook = _get_turbo_codebook(bits, dim).astype(np.float32)
    reconstructed = codebook[indices]  # (n, dim)

    # Inverse rotation: x_hat = reconstructed @ Π  (since Π is orthogonal, Π^{-1} = Π^T)
    rot = rotation_matrix.astype(np.float32)
    unrotated = reconstructed @ rot  # (n, dim)

    return unrotated * norms


# ---------------------------------------------------------------------------
# TurboQuant 2-bit packing (4 values per byte)
# ---------------------------------------------------------------------------


def _pack_turbo2(indices: np.ndarray) -> np.ndarray:
    """Pack 2-bit unsigned indices (0..3) into uint8.

    Four values per byte.  *indices* shape ``(n, dim)`` → ``(n, ceil(dim/4))``.
    """
    n, dim = indices.shape
    pad = (4 - dim % 4) % 4
    if pad:
        indices = np.concatenate(
            [indices, np.zeros((n, pad), dtype=indices.dtype)], axis=1
        )
    reshaped = indices.reshape(n, -1, 4)  # (n, groups, 4)
    packed = (
        reshaped[:, :, 0].astype(np.uint8)
        | (reshaped[:, :, 1].astype(np.uint8) << 2)
        | (reshaped[:, :, 2].astype(np.uint8) << 4)
        | (reshaped[:, :, 3].astype(np.uint8) << 6)
    )
    return packed


def _unpack_turbo2(packed: np.ndarray, dim: int) -> np.ndarray:
    """Unpack uint8 → 2-bit unsigned indices (0..3).

    Returns shape ``(n, dim)`` with dtype uint8.
    """
    v0 = packed & 0x03
    v1 = (packed >> 2) & 0x03
    v2 = (packed >> 4) & 0x03
    v3 = (packed >> 6) & 0x03
    n = packed.shape[0]
    interleaved = np.empty((n, packed.shape[1] * 4), dtype=np.uint8)
    interleaved[:, 0::4] = v0
    interleaved[:, 1::4] = v1
    interleaved[:, 2::4] = v2
    interleaved[:, 3::4] = v3
    return interleaved[:, :dim]


# ---------------------------------------------------------------------------
# TurboQuant 3-bit packing (8 values → 3 bytes, unsigned 0..7)
# ---------------------------------------------------------------------------


def _pack_turbo3(indices: np.ndarray) -> np.ndarray:
    """Pack 3-bit unsigned indices (0..7) into uint8.

    8 values per 3 bytes (24 bits).
    *indices* shape ``(n, dim)`` → ``(n, ceil(dim/8)*3)``.
    """
    n, dim = indices.shape
    pad = (8 - dim % 8) % 8
    if pad:
        indices = np.concatenate(
            [indices, np.zeros((n, pad), dtype=indices.dtype)], axis=1
        )
    groups = indices.shape[1] // 8
    vals = indices.astype(np.uint32).reshape(n, groups, 8)

    bits = np.zeros((n, groups), dtype=np.uint32)
    for i in range(8):
        bits |= vals[:, :, i] << (i * 3)

    packed = np.zeros((n, groups * 3), dtype=np.uint8)
    packed[:, 0::3] = (bits & 0xFF).astype(np.uint8)
    packed[:, 1::3] = ((bits >> 8) & 0xFF).astype(np.uint8)
    packed[:, 2::3] = ((bits >> 16) & 0xFF).astype(np.uint8)
    return packed


def _unpack_turbo3(packed: np.ndarray, dim: int) -> np.ndarray:
    """Unpack uint8 → 3-bit unsigned indices (0..7).

    Returns shape ``(n, dim)`` with dtype uint8.
    """
    n = packed.shape[0]
    groups = packed.shape[1] // 3

    bits = (
        packed[:, 0::3].astype(np.uint32)
        | (packed[:, 1::3].astype(np.uint32) << 8)
        | (packed[:, 2::3].astype(np.uint32) << 16)
    )

    vals = np.zeros((n, groups, 8), dtype=np.uint8)
    for i in range(8):
        vals[:, :, i] = ((bits >> (i * 3)) & 0x07).astype(np.uint8)

    return vals.reshape(n, groups * 8)[:, :dim]


# ---------------------------------------------------------------------------
# TurboQuant 4-bit packing (2 values per byte, unsigned 0..15)
# ---------------------------------------------------------------------------


def _pack_turbo4(indices: np.ndarray) -> np.ndarray:
    """Pack 4-bit unsigned indices (0..15) into uint8.  Two values per byte."""
    n, dim = indices.shape
    if dim % 2:
        indices = np.concatenate(
            [indices, np.zeros((n, 1), dtype=indices.dtype)], axis=1
        )
    low = indices[:, 0::2].astype(np.uint8)
    high = indices[:, 1::2].astype(np.uint8)
    return low | (high << 4)


def _unpack_turbo4(packed: np.ndarray, dim: int) -> np.ndarray:
    """Unpack uint8 → 4-bit unsigned indices (0..15)."""
    low = packed & 0x0F
    high = (packed >> 4) & 0x0F
    n = packed.shape[0]
    interleaved = np.empty((n, packed.shape[1] * 2), dtype=np.uint8)
    interleaved[:, 0::2] = low
    interleaved[:, 1::2] = high
    return interleaved[:, :dim]
